name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest

    strategy:
      matrix:
        platform:
          - macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mxcl/xcodebuild@v3
        with:
          platform: ${{ matrix.platform }}
          action: build
